version: "3"


services:
  postgresdb:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=testpass
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: ./docker/
      dockerfile: Dockerfile
    command: bash -c "
        sleep 10;
        pipenv run python manage.py makemigrations
        && pipenv run python manage.py migrate
        && pipenv run python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgresdb


