# Generated by Django 3.2.7 on 2021-09-03 10:57

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name': 'Офис', 'verbose_name_plural': 'Офисы'},
        ),
        migrations.AddField(
            model_name='office',
            name='address',
            field=models.CharField(default='', max_length=400, verbose_name='Адрес офиса'),
        ),
        migrations.AddField(
            model_name='office',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='office',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Название офиса'),
        ),
        migrations.AlterField(
            model_name='office',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Страна'),
        ),
    ]
