# Generated by Django 3.2.7 on 2021-09-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20210903_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='_companies_company_partners_+', to='companies.Company', verbose_name='Партнеры'),
        ),
    ]
